"""Canonical ROS topic names used by Triskel operator processes."""

ARM_COMMAND_TOPIC = "/arm_controller/joint_trajectory"
BASE_COMMAND_TOPIC = "/cmd_vel"
GRIPPER_COMMAND_TOPIC = "/gripper_controller/joint_trajectory"
JOINT_STATE_TOPIC = "/joint_states"
ODOMETRY_TOPIC = "/omni_base_controller/odom"
QUEST_JOY_TOPIC = "/triskel/teleop/meta_quest/joy"
QUEST_POSE_TOPIC = "/triskel/teleop/meta_quest/right_controller_pose"
SERVO_STATUS_TOPIC = "/servo_node/status"
TF_STATIC_TOPIC = "/tf_static"
TF_TOPIC = "/tf"
TOOL_COMMAND_TOPIC = "/servo_node/delta_twist_cmds"
VISUALIZATION_READY_TOPIC = "/triskel/visualization/ready"
