"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class actuator_health_report_t(object):

    __slots__ = ["timestamp", "num_actuators", "joint_names", "controllers", "actuator_ids", "healthy", "temperatures_celsius", "issues", "error"]

    __typenames__ = ["int64_t", "int32_t", "string", "string", "int32_t", "int32_t", "double", "string", "string"]

    __dimensions__ = [None, None, ["num_actuators"], ["num_actuators"], ["num_actuators"], ["num_actuators"], ["num_actuators"], ["num_actuators"], None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.num_actuators = 0
        """ LCM Type: int32_t """
        self.joint_names = []
        """ LCM Type: string[num_actuators] """
        self.controllers = []
        """ LCM Type: string[num_actuators] """
        self.actuator_ids = []
        """ LCM Type: int32_t[num_actuators] """
        self.healthy = []
        """ LCM Type: int32_t[num_actuators] """
        self.temperatures_celsius = []
        """ LCM Type: double[num_actuators] """
        self.issues = []
        """ LCM Type: string[num_actuators] """
        self.error = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(actuator_health_report_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.num_actuators))
        for i0 in range(self.num_actuators):
            __joint_names_encoded = self.joint_names[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__joint_names_encoded)+1))
            buf.write(__joint_names_encoded)
            buf.write(b"\0")
        for i0 in range(self.num_actuators):
            __controllers_encoded = self.controllers[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__controllers_encoded)+1))
            buf.write(__controllers_encoded)
            buf.write(b"\0")
        buf.write(struct.pack('>%di' % self.num_actuators, *self.actuator_ids[:self.num_actuators]))
        buf.write(struct.pack('>%di' % self.num_actuators, *self.healthy[:self.num_actuators]))
        buf.write(struct.pack('>%dd' % self.num_actuators, *self.temperatures_celsius[:self.num_actuators]))
        for i0 in range(self.num_actuators):
            __issues_encoded = self.issues[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__issues_encoded)+1))
            buf.write(__issues_encoded)
            buf.write(b"\0")
        __error_encoded = self.error.encode('utf-8')
        buf.write(struct.pack('>I', len(__error_encoded)+1))
        buf.write(__error_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != actuator_health_report_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return actuator_health_report_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = actuator_health_report_t()
        self.timestamp, self.num_actuators = struct.unpack(">qi", buf.read(12))
        self.joint_names = []
        for i0 in range(self.num_actuators):
            __joint_names_len = struct.unpack('>I', buf.read(4))[0]
            self.joint_names.append(buf.read(__joint_names_len)[:-1].decode('utf-8', 'replace'))
        self.controllers = []
        for i0 in range(self.num_actuators):
            __controllers_len = struct.unpack('>I', buf.read(4))[0]
            self.controllers.append(buf.read(__controllers_len)[:-1].decode('utf-8', 'replace'))
        self.actuator_ids = struct.unpack('>%di' % self.num_actuators, buf.read(self.num_actuators * 4))
        self.healthy = struct.unpack('>%di' % self.num_actuators, buf.read(self.num_actuators * 4))
        self.temperatures_celsius = struct.unpack('>%dd' % self.num_actuators, buf.read(self.num_actuators * 8))
        self.issues = []
        for i0 in range(self.num_actuators):
            __issues_len = struct.unpack('>I', buf.read(4))[0]
            self.issues.append(buf.read(__issues_len)[:-1].decode('utf-8', 'replace'))
        __error_len = struct.unpack('>I', buf.read(4))[0]
        self.error = buf.read(__error_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if actuator_health_report_t in parents: return 0
        tmphash = (0x184b386c09fb9d69) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if actuator_health_report_t._packed_fingerprint is None:
            actuator_health_report_t._packed_fingerprint = struct.pack(">Q", actuator_health_report_t._get_hash_recursive([]))
        return actuator_health_report_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", actuator_health_report_t._get_packed_fingerprint())[0]

