"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class homing_target_t(object):

    __slots__ = ["timestamp", "num_positions", "target_position"]

    __typenames__ = ["int64_t", "int32_t", "double"]

    __dimensions__ = [None, None, ["num_positions"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.num_positions = 0
        """ LCM Type: int32_t """
        self.target_position = []
        """ LCM Type: double[num_positions] """

    def encode(self):
        buf = BytesIO()
        buf.write(homing_target_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.num_positions))
        buf.write(struct.pack('>%dd' % self.num_positions, *self.target_position[:self.num_positions]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != homing_target_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return homing_target_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = homing_target_t()
        self.timestamp, self.num_positions = struct.unpack(">qi", buf.read(12))
        self.target_position = struct.unpack('>%dd' % self.num_positions, buf.read(self.num_positions * 8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if homing_target_t in parents: return 0
        tmphash = (0x101a72f16ca3c4e1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if homing_target_t._packed_fingerprint is None:
            homing_target_t._packed_fingerprint = struct.pack(">Q", homing_target_t._get_hash_recursive([]))
        return homing_target_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", homing_target_t._get_packed_fingerprint())[0]

