"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class logging_status_t(object):

    __slots__ = ["timestamp", "state", "file_name", "error"]

    __typenames__ = ["int64_t", "string", "string", "string"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.state = ""
        """ LCM Type: string """
        self.file_name = ""
        """ LCM Type: string """
        self.error = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(logging_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __state_encoded = self.state.encode('utf-8')
        buf.write(struct.pack('>I', len(__state_encoded)+1))
        buf.write(__state_encoded)
        buf.write(b"\0")
        __file_name_encoded = self.file_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__file_name_encoded)+1))
        buf.write(__file_name_encoded)
        buf.write(b"\0")
        __error_encoded = self.error.encode('utf-8')
        buf.write(struct.pack('>I', len(__error_encoded)+1))
        buf.write(__error_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != logging_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return logging_status_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = logging_status_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __state_len = struct.unpack('>I', buf.read(4))[0]
        self.state = buf.read(__state_len)[:-1].decode('utf-8', 'replace')
        __file_name_len = struct.unpack('>I', buf.read(4))[0]
        self.file_name = buf.read(__file_name_len)[:-1].decode('utf-8', 'replace')
        __error_len = struct.unpack('>I', buf.read(4))[0]
        self.error = buf.read(__error_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if logging_status_t in parents: return 0
        tmphash = (0x4005acbe2adcab40) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if logging_status_t._packed_fingerprint is None:
            logging_status_t._packed_fingerprint = struct.pack(">Q", logging_status_t._get_hash_recursive([]))
        return logging_status_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", logging_status_t._get_packed_fingerprint())[0]
