"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class motor_temperature_t(object):

    __slots__ = ["name", "temperature"]

    __typenames__ = ["string", "double"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.name = ""
        """ LCM Type: string """
        self.temperature = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(motor_temperature_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">d", self.temperature))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motor_temperature_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motor_temperature_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = motor_temperature_t()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.temperature = struct.unpack(">d", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if motor_temperature_t in parents: return 0
        tmphash = (0x2b7e162dae9158) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if motor_temperature_t._packed_fingerprint is None:
            motor_temperature_t._packed_fingerprint = struct.pack(">Q", motor_temperature_t._get_hash_recursive([]))
        return motor_temperature_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", motor_temperature_t._get_packed_fingerprint())[0]

