"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class node_rate_sample_t(object):

    __slots__ = ["timestamp", "node_name", "pid", "target_rate_hz", "measured_rate_hz"]

    __typenames__ = ["int64_t", "string", "int64_t", "double", "double"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.node_name = ""
        """ LCM Type: string """
        self.pid = 0
        """ LCM Type: int64_t """
        self.target_rate_hz = 0.0
        """ LCM Type: double """
        self.measured_rate_hz = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(node_rate_sample_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __node_name_encoded = self.node_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__node_name_encoded)+1))
        buf.write(__node_name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">qdd", self.pid, self.target_rate_hz, self.measured_rate_hz))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != node_rate_sample_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return node_rate_sample_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = node_rate_sample_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __node_name_len = struct.unpack('>I', buf.read(4))[0]
        self.node_name = buf.read(__node_name_len)[:-1].decode('utf-8', 'replace')
        self.pid, self.target_rate_hz, self.measured_rate_hz = struct.unpack(">qdd", buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if node_rate_sample_t in parents: return 0
        tmphash = (0xd7e814de746b53f3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if node_rate_sample_t._packed_fingerprint is None:
            node_rate_sample_t._packed_fingerprint = struct.pack(">Q", node_rate_sample_t._get_hash_recursive([]))
        return node_rate_sample_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", node_rate_sample_t._get_packed_fingerprint())[0]
