"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class orchestrator_mode_t(object):

    __slots__ = ["timestamp", "mode"]

    __typenames__ = ["int64_t", "string"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.mode = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(orchestrator_mode_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __mode_encoded = self.mode.encode('utf-8')
        buf.write(struct.pack('>I', len(__mode_encoded)+1))
        buf.write(__mode_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != orchestrator_mode_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return orchestrator_mode_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = orchestrator_mode_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __mode_len = struct.unpack('>I', buf.read(4))[0]
        self.mode = buf.read(__mode_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if orchestrator_mode_t in parents: return 0
        tmphash = (0x3b11de6b3ba2016b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if orchestrator_mode_t._packed_fingerprint is None:
            orchestrator_mode_t._packed_fingerprint = struct.pack(">Q", orchestrator_mode_t._get_hash_recursive([]))
        return orchestrator_mode_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", orchestrator_mode_t._get_packed_fingerprint())[0]

