"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class orchestrator_event_t(object):

    __slots__ = ["timestamp", "kind"]

    __typenames__ = ["int64_t", "string"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.kind = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(orchestrator_event_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __kind_encoded = self.kind.encode('utf-8')
        buf.write(struct.pack('>I', len(__kind_encoded)+1))
        buf.write(__kind_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != orchestrator_event_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return orchestrator_event_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = orchestrator_event_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __kind_len = struct.unpack('>I', buf.read(4))[0]
        self.kind = buf.read(__kind_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if orchestrator_event_t in parents: return 0
        tmphash = (0x3b11de6b37aded69) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if orchestrator_event_t._packed_fingerprint is None:
            orchestrator_event_t._packed_fingerprint = struct.pack(">Q", orchestrator_event_t._get_hash_recursive([]))
        return orchestrator_event_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", orchestrator_event_t._get_packed_fingerprint())[0]

