"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class robot_joint_command_t(object):

    __slots__ = ["timestamp", "num_joints", "joint_positions"]

    __typenames__ = ["int64_t", "int32_t", "double"]

    __dimensions__ = [None, None, ["num_joints"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.num_joints = 0
        """ LCM Type: int32_t """
        self.joint_positions = []
        """ LCM Type: double[num_joints] """

    def encode(self):
        buf = BytesIO()
        buf.write(robot_joint_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.num_joints))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.joint_positions[:self.num_joints]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_joint_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_joint_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = robot_joint_command_t()
        self.timestamp, self.num_joints = struct.unpack(">qi", buf.read(12))
        self.joint_positions = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if robot_joint_command_t in parents: return 0
        tmphash = (0xf6e2dcba3a9aeab3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if robot_joint_command_t._packed_fingerprint is None:
            robot_joint_command_t._packed_fingerprint = struct.pack(">Q", robot_joint_command_t._get_hash_recursive([]))
        return robot_joint_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_joint_command_t._get_packed_fingerprint())[0]

