"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import humanoid.types.lcm

class robot_command_t(object):

    __slots__ = ["timestamp", "num_joints", "joint_positions"]

    __typenames__ = ["int64_t", "int32_t", "humanoid.types.lcm.joint_position_t"]

    __dimensions__ = [None, None, ["num_joints"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.num_joints = 0
        """ LCM Type: int32_t """
        self.joint_positions = []
        """ LCM Type: humanoid.types.lcm.joint_position_t[num_joints] """

    def encode(self):
        buf = BytesIO()
        buf.write(robot_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.num_joints))
        for i0 in range(self.num_joints):
            assert self.joint_positions[i0]._get_packed_fingerprint() == humanoid.types.lcm.joint_position_t._get_packed_fingerprint()
            self.joint_positions[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = robot_command_t()
        self.timestamp, self.num_joints = struct.unpack(">qi", buf.read(12))
        self.joint_positions = []
        for i0 in range(self.num_joints):
            self.joint_positions.append(humanoid.types.lcm.joint_position_t._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if robot_command_t in parents: return 0
        newparents = parents + [robot_command_t]
        tmphash = (0xc0cc70d9a8f769e9+ humanoid.types.lcm.joint_position_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if robot_command_t._packed_fingerprint is None:
            robot_command_t._packed_fingerprint = struct.pack(">Q", robot_command_t._get_hash_recursive([]))
        return robot_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_command_t._get_packed_fingerprint())[0]

