"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class robot_tool_command_t(object):

    __slots__ = ["timestamp", "position", "quaternion"]

    __typenames__ = ["int64_t", "double", "double"]

    __dimensions__ = [None, [3], [4]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.position = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: double[3] """
        self.quaternion = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: double[4] """

    def encode(self):
        buf = BytesIO()
        buf.write(robot_tool_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3d', *self.position[:3]))
        buf.write(struct.pack('>4d', *self.quaternion[:4]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_tool_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_tool_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = robot_tool_command_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.position = struct.unpack('>3d', buf.read(24))
        self.quaternion = struct.unpack('>4d', buf.read(32))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if robot_tool_command_t in parents: return 0
        tmphash = (0x2f2ae79e4be50733) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if robot_tool_command_t._packed_fingerprint is None:
            robot_tool_command_t._packed_fingerprint = struct.pack(">Q", robot_tool_command_t._get_hash_recursive([]))
        return robot_tool_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_tool_command_t._get_packed_fingerprint())[0]

