"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class robot_state_t(object):

    __slots__ = ["timestamp", "num_joints", "num_positions", "num_velocities", "joint_positions", "joint_velocities", "motor_temperatures"]

    __typenames__ = ["int64_t", "int32_t", "int32_t", "int32_t", "double", "double", "double"]

    __dimensions__ = [None, None, None, None, ["num_positions"], ["num_velocities"], ["num_joints"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.num_joints = 0
        """ LCM Type: int32_t """
        self.num_positions = 0
        """ LCM Type: int32_t """
        self.num_velocities = 0
        """ LCM Type: int32_t """
        self.joint_positions = []
        """ LCM Type: double[num_positions] """
        self.joint_velocities = []
        """ LCM Type: double[num_velocities] """
        self.motor_temperatures = []
        """ LCM Type: double[num_joints] """

    def encode(self):
        buf = BytesIO()
        buf.write(robot_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiii", self.timestamp, self.num_joints, self.num_positions, self.num_velocities))
        buf.write(struct.pack('>%dd' % self.num_positions, *self.joint_positions[:self.num_positions]))
        buf.write(struct.pack('>%dd' % self.num_velocities, *self.joint_velocities[:self.num_velocities]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.motor_temperatures[:self.num_joints]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_state_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = robot_state_t()
        self.timestamp, self.num_joints, self.num_positions, self.num_velocities = struct.unpack(">qiii", buf.read(20))
        self.joint_positions = struct.unpack('>%dd' % self.num_positions, buf.read(self.num_positions * 8))
        self.joint_velocities = struct.unpack('>%dd' % self.num_velocities, buf.read(self.num_velocities * 8))
        self.motor_temperatures = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if robot_state_t in parents: return 0
        tmphash = (0x5250b4fdf77aa59e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if robot_state_t._packed_fingerprint is None:
            robot_state_t._packed_fingerprint = struct.pack(">Q", robot_state_t._get_hash_recursive([]))
        return robot_state_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_state_t._get_packed_fingerprint())[0]

