"""Generate browser constants from the Python API contract."""

import argparse
import json
from enum import StrEnum

from humanoid.orchestrator.constants import TELEOP_PROCESSES
from humanoid.types.logging import LoggingState
from humanoid.types.orchestrator import Mode, OrchestratorParameter
from humanoid.types.process import ProcessAction, ProcessName, Runtime
from humanoid.types.replay import ReplayOutcome
from humanoid.types.simulation import MujocoScene
from humanoid.ui.constants import STATIC_ROOT, ApiRoute, PayloadKey

OUTPUT_PATH = STATIC_ROOT / "js" / "constants.js"
GENERATED_HEADER = """// Generated by `uv run python scripts/generate_js_constants.py`.
// Python enums and UI routes are the source of truth. Do not edit this file manually.
"""


def render_javascript_constants() -> str:
    """Render the JavaScript module consumed by the browser and Node tests."""
    sections = [
        GENERATED_HEADER,
        _enum_object("Runtime", Runtime),
        _enum_object("ProcessName", ProcessName),
        _enum_object("ProcessAction", ProcessAction),
        _enum_object("Mode", Mode),
        _enum_object("LoggingState", LoggingState),
        _enum_object("ReplayOutcome", ReplayOutcome),
        _enum_object("MujocoScene", MujocoScene),
        _enum_object("OrchestratorParameter", OrchestratorParameter),
        _enum_object("PayloadKey", PayloadKey),
        _enum_object("ApiRoute", ApiRoute),
        _busy_keys(),
        _teleop_processes(),
        _api_routes(),
    ]
    return "\n".join(sections)


def _enum_object(name: str, enum_type: type[StrEnum]) -> str:
    entries = "\n".join(f"  {member.name}: {json.dumps(member.value)}," for member in enum_type)
    return f"export const {name} = Object.freeze({{\n{entries}\n}});\n"


def _busy_keys() -> str:
    return """export const BusyKey = Object.freeze({
  RUNTIME: ApiRoute.RUNTIME,
  ROBOT: ApiRoute.ROBOT,
  SCENE: ApiRoute.SCENE,
  LOGGING: ApiRoute.LOGGING,
  REPLAY: ApiRoute.REPLAY,
  ORCHESTRATOR: ApiRoute.ORCHESTRATOR,
});
"""


def _teleop_processes() -> str:
    entries = "\n".join(f"  ProcessName.{process.name}," for process in TELEOP_PROCESSES.values())
    return f"export const TELEOP_PROCESSES = Object.freeze([\n{entries}\n]);\n"


def _api_routes() -> str:
    return """export const API = Object.freeze({
  STATUS: ApiRoute.STATUS,
  RUNTIME: ApiRoute.RUNTIME,
  ROBOT: ApiRoute.ROBOT,
  SCENE: ApiRoute.SCENE,
  logging(action) {
    return resolveRoute(ApiRoute.LOGGING, { action });
  },
  replay(action) {
    return resolveRoute(ApiRoute.REPLAY, { action });
  },
  ORCHESTRATOR: ApiRoute.ORCHESTRATOR,
  process(name, action) {
    return resolveRoute(ApiRoute.PROCESSES, { name, action });
  },
});

function resolveRoute(route, parameters) {
  return Object.entries(parameters).reduce(
    (result, [name, value]) =>
      result.replace(`<${name}>`, encodeURIComponent(value)),
    route,
  );
}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated JavaScript constants are not current.",
    )
    args = parser.parse_args()
    generated = render_javascript_constants()

    if args.check:
        current = OUTPUT_PATH.read_text() if OUTPUT_PATH.exists() else None
        if current != generated:
            raise SystemExit(
                "Generated UI constants are stale. Run "
                "`uv run python scripts/generate_js_constants.py`."
            )
        return

    OUTPUT_PATH.write_text(generated)


if __name__ == "__main__":
    main()
